[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
board_build.ldscript = eagle.flash.4m3m.ld
build_flags =
    -I include
    -I fonts
extra_scripts = pre:scripts/ensure_secrets.py
lib_deps =