#!/usr/bin/env python3
"""Generate lunar_data.inc for ESP8266 firmware (2020-01-01 .. 2035-12-31)."""
from datetime import date, datetime, timedelta

try:
    from zhdate import ZhDate
except ImportError:
    raise SystemExit("pip install zhdate")

START = date(2020, 1, 1)
END = date(2035, 12, 31)

rows = []
d = START
while d <= END:
    z = ZhDate.from_datetime(datetime(d.year, d.month, d.day))
    leap = 1 if z.leap_month else 0
    rows.append((d.year, d.month, d.day, z.lunar_year, z.lunar_month, z.lunar_day, leap))
    d += timedelta(days=1)

print("days", len(rows))

out_path = "src/lunar_data.inc"
with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Auto-generated by scripts/gen_lunar_table.py — do not edit.\n")
    f.write("// Solar civil dates in China (UTC+8) -> lunar year/month/day + leap flag.\n")
    f.write(f"// Range: {START} .. {END} ({len(rows)} days).\n")
    f.write("static const LunarEntry kLunarTable[] PROGMEM = {\n")
    for i, r in enumerate(rows):
        y, m, d, ly, lm, ld, leap = r
        comma = "," if i < len(rows) - 1 else ""
        f.write(f"    {{{y}, {m}, {d}, {ly}, {lm}, {ld}, {leap}}}{comma}\n")
    f.write("};\n")
    f.write(f"static const uint16_t kLunarTableDays = {len(rows)};\n")

print("wrote", out_path)